cats99_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :edit, :update, :create]

  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end
end

cats99_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99_project/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'action_view'
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    COLORS = %w(brown yellow white black orange blue red).freeze()
    validates :birth_date, :color, :name, :sex, :description, presence: true
    validates :sex, inclusion: { in: %w(M F), message: "Can only be either M or F" }
    validates :color, inclusion: { in: COLORS, message: "Can only be a valid color" }

    def age
        time_ago_in_words(birth_date)
    end

    has_many :cat_rental_requests, dependent: :destroy
end

cats99_project/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CatRentalRequest < ApplicationRecord

    STATUS_CODES = %w(PENDING APPROVED DENIED).freeze

    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: {in: STATUS_CODES, message: "must be a status code"}
    validate :does_not_overlap_approved_request

    belongs_to :cat

    def overlapping_requests
        # find all overlapping cat rental requests of the same cat
        # we have cat_id in our instance
        # Case 1
        # this:     |______|
        # ol:   |____________|

        # Case 2
        # this:    |______|
        # ol:           |________|

        # Case 3
        # this:    |______|
        # ol:  |________|

        # Case 4
        # this:    |____________|
        # ol:         |______|

        # debugger
        CatRentalRequest
            .select('*')
            .where(cat_id: self.cat_id)
            .where.not(id: self.id)
            .where.not('start_date > ? OR end_date < ?', end_date, start_date)
    end

    def overlapping_approved_requests
        # debugger
        self.overlapping_requests.where(status: 'APPROVED')
    end

    def does_not_overlap_approved_request
        # debugger
       if self.overlapping_approved_requests.exists? && self.status != 'DENIED'
            errors[:base] << 'Conflict in approved request'
       end
    end

    def overlapping_pending_requests
        self.overlapping_requests.where(status: 'PENDING')
    end

    def approve!
        ActiveRecord::Base.transaction do
            self.status = 'APPROVED'
            self.save!
            self.overlapping_pending_requests.each do |request|
                request.status = 'DENIED'
                request.save!
            end
        end
    end

    def deny!
        self.status = 'DENIED'
        self.save!
    end

    def pending?
        self.status == 'PENDING'
    end
end

cats99_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99_project/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
    def new
        @cat_rental_request = CatRentalRequest.new
        render :new
    end

    def create
        @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
        if @cat_rental_request.save
            redirect_to cat_url(Cat.find_by(id: @cat_rental_request.cat_id))
        else
            flash.now[:errors] = @cat_rental_request.errors.full_messages
            render :new
        end
    end

    def approve
        @cat_rental_request = CatRentalRequest.includes(:cat).find(params[:id])
        @cat_rental_request.approve!
        redirect_to cat_url(@cat_rental_request.cat)
    end

    def deny
        @cat_rental_request = CatRentalRequest.includes(:cat).find(params[:id])
        @cat_rental_request.deny!
        redirect_to cat_url(@cat_rental_request.cat)
    end

    private
    def cat_rental_request_params
        params.require(:cat_rental_request)
            .permit(:cat_id, :start_date, :end_date, :status)
    end
end

cats99_project/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all.order(:id)
        render :index
    end

    def show 
        @cat = Cat.find_by(id: params[:id])
        if @cat
            render :show
        else
            redirect_to cats_url
        end
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create 
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else
            flash.now[:errors] = @cat.errors.full_messages
            render :new
        end
    end

    def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end


    def update
        @cat = Cat.find_by(id: params[:id])

        if @cat.update_attributes(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
        
    end

    private
    def cat_params
        params.require(:cat).permit(:name, :color, :birth_date, :sex, :description)
    end
end 

cats99_project/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99_project/app/views/cat_rental_requests/new.html.erb
<h1>Create a new request</h1>

<%= render "shared/errors" %>

<form class="ui form" action="<%= cat_rental_requests_url %>" method = "POST">
    <div class="field">
        <label for="cats">Choose a cat to rent:</label>
        <select name="cat_rental_request[cat_id]" id="cats">
            <option value="Select a cat" selected disabled>Select a cat</option>
            <% Cat.all.each do |cat| %>
            <option value="<%= cat.id %>"> <%= cat.name %> </option>
            <% end %>
        </select>
    </div>

    <br>

    <div class="field">
        <label for="start_date" >Start Date:</label>
        <input id="start_date" type="date" name="cat_rental_request[start_date]" value="<%= @cat_rental_request.start_date %>" >

        <label for="end_date" >End Date:</label>    
        <input id="end_date" type="date" name="cat_rental_request[end_date]" value="<%= @cat_rental_request.end_date %>" >
    </div>

    <br>

    <input class="ui button" type="submit" value="Create Request">

</form>


<%# name is important! %>

cats99_project/app/views/cats/_form.html.erb
<% redirect_url = ( cat.persisted? ? cat_url(cat) : cats_url ) %>

<form action="<%= redirect_url %>" method="POST" class="ui form">
    
    <% if cat.persisted? %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>
    <div class="field" >
        <label for="name">Name</label>
        <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">
    </div>

    <br>

    <div class="field" >
        <label for="bd">Birth Date</label>
        <input type="date" id="bd" name="cat[birth_date]" value="<%= cat.birth_date %>">
    </div>

    <br>

    <div class="field">
    <label for="colors">Select a color:</label>
    <select id="colors" name="cat[color]">
        <option disabled <%= cat.color ? "" : "selected" %> >Select a color</option>
        <% Cat::COLORS.each do |color| %>
            <option value="<%= color %>" <%= cat.color == color ? "selected": "" %> ><%= color.capitalize %></option>
        <% end %>
    </select>
    </div>

    <br>

    
    <div class="field">
        <label for="dropdown"> Select a sex:</label>   
        <div id="dropdown">
            <label for="male">Male</label>
            <input type="radio" id="male" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked": "" %> >
            <label for="female">Female</label>
            <input type="radio" id="female" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked": "" %> >
        </div>
    </div>

    <br>
    <div class="field">
        <label for="description">Description</label>
        <textarea style="resize: none;" id="description" name="cat[description]">
            <%= cat.description %>
        </textarea>
    </div>
   
    <input class="ui button" type="submit" value= <%= cat.persisted? ? "Edit Cat" : "Create Cat" %>  >

</form>

cats99_project/app/views/cats/edit.html.erb
<h1 class="ui container">Edit-A-Cat</h1>
<%= render "shared/errors" %>
<%= render "form", cat: @cat %>

cats99_project/app/views/cats/index.html.erb
<div class="ui middle aligned selection list">

<h1>Cats</h1>

<ul style="list-style:none;">
    <% @cats.each do |cat| %>
    <li class="item"> 
        <h3><a class="header" href="<%= cat_url(cat) %>"><%= cat.name %></a></h3>
    </li>
    <% end %>
</ul>

</div>

<a style="background-color:#8fcbff;" class="ui button" href="<%= new_cat_url %>">+ Build-A-Cat</a>

cats99_project/app/views/cats/new.html.erb
<h1 class="ui container">Build-A-Cat</h1>
<%= render "shared/errors" %>
<%= render "form", cat: @cat %>

cats99_project/app/views/cats/show.html.erb
<table class="ui celled padded table">
    <thead>
        <tr>
            <th class="single line">
                Name
            </th>
             <th>
                Age
            </th>
             <th>
                Color
            </th>
             <th>
                Sex
            </th>
             <th>
                Description
            </th>
            <th>
                Rental Requests
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <%= @cat.name %>
            </td>
             <td>
                <%= @cat.age %>
            </td>
             <td>
                <%= @cat.color %>
            </td>
             <td>
                <%= @cat.sex %>
            </td>
             <td>
                <%= @cat.description %>
            </td>
            <td>
                <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
                Start Date:<%= request.start_date %>
                End Date:<%= request.end_date %>
                Status: <%= request.status %>
                <% if request.pending? %>
                    <form style="display:inline;" action="<%= approve_cat_rental_request_url(request) %>" method="POST">
                        <input class="ui button" type="submit" value="Approve" %>
                    </form>
                
                    <form style="display:inline;" action="<%= deny_cat_rental_request_url(request) %>" method="POST">
                        <input class="ui button" type="submit" value="Deny" %>
                    </form>
                <% end %>
                <br>
                <% end %>
                <a class="ui button" type="submit" href="<%= new_cat_rental_request_url %>">New Rental Request</a>
            </td>
            
        </tr>
    </tbody>
</table>
<a class="ui button" type="submit" href="<%= edit_cat_url %>">Edit</a>

cats99_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
  </head>

  <body class="ui container">
    <%= yield %>
  </body>
</html>

cats99_project/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <div class="ui error message">
    <div class="header">
      There were some errors with your submission
    </div>
    <ul class="list">
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>